name: Android Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Build APK
        run: ./gradlew assembleRelease

      # https://github.com/marketplace/actions/sign-android-release-2
      - name: Sign APK
        id: sign_app
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedFile}}

      # https://github.com/marketplace/actions/gh-release
      - name: Release APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{steps.sign_app.outputs.signedFile}}
